### ISSUE TITLE
.env and prisma

### ISSUE THREAD

**Issue by caillou** [teachen-ch/voty#22]
Figure out a way to not duplicate the `.env` file.

**Comment by stefnnn** [comment]
this will solve itself eventually with https://github.com/prisma/prisma/issues/3865 or https://github.com/prisma/prisma/issues/3720

**Comment by stefnnn** [comment]
solved with https://github.com/teachen-ch/voty/commit/af55cd308ea5507323ddc2fc164f579a3e5daa79
