### ISSUE TITLE
Automatic Certificate-Renewal fails

### ISSUE THREAD

**Issue by stefnnn** [teachen-ch/voty#39]
Because it can't bind to port 80. Should we stop nginx, run certbot and restart it again? Sounds a bit risky. Next expire will be in Jan 2020

**Comment by stefnnn** [comment]
need to install the nginx certbot plugin
```
apt install python3-certbot-nginx
```

and run automatic update with it:
```
certbot -d "votyapp.ch,www.votyapp.ch" --nginx certonly
```

Now that need to go into the ansible scripts at some point

**Comment by stefnnn** [comment]
This could be fixed. Let's reopen if needed

**Comment by caillou** [comment]
You could use traefik in front of the app and let it take care of the certs.

Additionally, you can then setup the docker network using labels.

https://github.com/IronicBadger/infra/blob/master/dev/traefik/docker-compose.yaml

**Comment by stefnnn** [comment]
Cool! I'll have a look at traefik. The certificates are already managed automatically by an ansible role (https://github.com/geerlingguy/ansible-role-certbot), which automatically installs a cron-job. Currently nginx is outside of docker (why so ever), so replacing it with traefik and going to an all-docker setup might be a good idea.
